name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - run: docker compose up -d

      - run: docker exec tasksflow-dev rye sync

      - run: docker exec tasksflow-dev rye test -- -s